#!/bin/bash -e

if [ $# -lt 2 ]; then
    echo "usage: $0 <source> <name> [<src-branch>]"
    exit 1
fi

source=$1
name=$2

if [ -n "$3" ]; then
    branch=$3
else
    branch=main
fi

mkdir $name

make-wt() {
    git -C $source/$1 worktree prune
    git -C $source/$1 worktree add -b $name $(pwd)/$name/$1 $branch
}

make-wt swift-llbuild
make-wt swift-build
make-wt swift-package-manager
make-wt sourcekit-lsp

mkdir -p $name/$name.xcworkspace

cat > $name/$name.xcworkspace/contents.xcworkspacedata <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<Workspace
   version = "1.0">
   <FileRef
      location = "group:swift-llbuild">
   </FileRef>
   <FileRef
      location = "group:swift-build">
   </FileRef>
   <FileRef
      location = "group:swift-package-manager">
   </FileRef>
   <FileRef
      location = "group:sourcekit-lsp">
   </FileRef>
</Workspace>
EOF
