#!/bin/bash -e

if [ $# -lt 1 ]; then
    echo "usage: $0 <name> [<src-branch>]"
    exit 1
fi

source=bare
name=$1

if [ -n "$2" ]; then
    branch=$2
else
    branch=main
fi

mkdir $name
cd $name

clone() {
    git clone https://github.com/swiftlang/$1 -b $branch
    cd $1
    git remote add work git@github.com:dschaefer2/$1
    git checkout -b $name
    gh repo set-default https://github.com/swiftlang/$1
    cd ..
}

clone swift-build
clone swift-package-manager
clone sourcekit-lsp

mkdir -p $name.xcworkspace

cat > $name.xcworkspace/contents.xcworkspacedata <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<Workspace
   version = "1.0">
   <FileRef
      location = "group:swift-build">
   </FileRef>
   <FileRef
      location = "group:swift-package-manager">
   </FileRef>
   <FileRef
      location = "group:sourcekit-lsp">
   </FileRef>
</Workspace>
EOF
