#!/bin/bash -e

if [ $# -lt 2 ]; then
    echo "usage: $0 <source> <name>"
    exit 1
fi

source=$1
name=$2

rm-wt() {
    echo $1
    if [ -d $name/$1 ]; then
        git -C $source/$1 worktree remove $(pwd)/$name/$1
    fi
    git -C $source/$1 branch -D $name
}

rm-wt swift-llbuild
rm-wt swift-build
rm-wt swift-package-manager
rm-wt sourcekit-lsp

rm -fr $name

