#!/bin/bash

if [ $# -lt 1 ]; then
    echo "usage: $0 <source>"
    exit 1
fi

source=bare
name=$1

rm-wt() {
    echo $1
    git -C $source/$1.git worktree remove $(pwd)/$name/$1
    git -C $source/$1.git branch -D $name
}

rm-wt swift-build
rm-wt swift-package-manager
rm-wt sourcekit-lsp

rm -fr $name

